#!/bin/bash
#Paranda/Kohenda antud praktikumis esimene skript nii, et ta ei küsi kasuja
#käest andmed, vaid need tuleb sisestada skripti käivitamisel. Juhul, kui
#käivitamisel andmed ei määra(kasutaja käivitab skripti ilma
#parameetrita/täis_arvuta, või need on rohkem kui üks),
#siis tuleb väljastada seletav teade. Skripti faili nime määra paarsus


#echo -n "Sisesta suvaline täisarv:"
read arv
#arvutame jääk 2-ga jagamisel
jaak=$(( $arv % 2 ))
# 4 % 2 => 0 -> siis arv on paaris
# 5 % 2 => 1 -> siis arv on paaritu
	if [ $jaak -eq 0 ]
	then
    	echo "$arv on paaris"
	else
    	echo "$arv on paaritu"
	fi

# tingimus kontroll on lõppenud

